name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  generate-build-matrix:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.generate.outputs.matrix }}
        matrix_variants: ${{ steps.generate.outputs.matrix_variants }}
        build_base_images: ${{ steps.generate.outputs.build_base_images }}
        build_bamboo_variants: ${{ steps.generate.outputs.build_bamboo_variants }} 
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 2
        - name: generate
          id: generate
          run: |
            bash ./generate_build_matrix.sh

  buildx:
    name: Build and Push the Docker Images
    runs-on: ubuntu-latest

    needs: generate-build-matrix
    if: needs.generate-build-matrix.outputs.build_base_images == 'yes'

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-build-matrix.outputs.matrix) }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: artemis-${{ matrix.name }}
          restore-keys: |
            artemis-${{ matrix.name }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ matrix.name }}
          file: ./${{ matrix.name }}/Dockerfile
          build-args: VERSION=${{ matrix.version }}
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/ls1intum/artemis-${{ matrix.name }}:latest,ghcr.io/ls1intum/artemis-${{ matrix.name }}:${{ matrix.version }}
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-bamboo-variants:
    name: Build and Push the Docker Images for the Bamboo variants
    runs-on: ubuntu-latest

    needs: [ buildx, generate-build-matrix ]
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled') &&
      !contains(needs.*.result, 'failure') &&
      needs.generate-build-matrix.outputs.build_bamboo_variants == 'yes'

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-build-matrix.outputs.matrix_variants) }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: artemis-bamboo-${{ matrix.name }}
          restore-keys: |
            artemis-bamboo-${{ matrix.name }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./bamboo/${{ matrix.name }}
          file: ./bamboo/${{ matrix.name }}/Dockerfile
          build-args: VERSION=${{ matrix.version }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ghcr.io/ls1intum/artemis-bamboo:latest-${{ matrix.name }},ghcr.io/ls1intum/artemis-bamboo:${{ matrix.version }}-${{ matrix.name }}
          labels: "runnumber=${GITHUB_RUN_ID}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
